PREFIX wu: <http://www.semanticweb.org/zerda/ontologies/2025/6/ontology_painkiller/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?painkillerLabel (COUNT(?patient) AS ?patientCount)
WHERE {
  ?patient a wu:Patient ;
           wu:patientAge ?age ;
           wu:patientExperiencedSideEffect ?sideEffect .


  ?sideEffect rdfs:label ?sideEffectLabel .
  FILTER(?sideEffectLabel IN (
      "Hyperkalaemia"@en, "Lactic acidosis"@en, "Thrombocytopenia"@en, 
      "Ventricular fibrillation"@en, "Drug dependence"@en
  ))

 
  ?report wu:reportInvolvesPatient ?patient .
  ?report wu:reportConcernsDrug ?drug .
  ?drug rdfs:label ?painkillerLabel .
}
GROUP BY ?painkillerLabel
ORDER BY DESC(?patientCount)