PREFIX wu: <http://www.semanticweb.org/zerda/ontologies/2025/6/ontology_painkiller/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT (COUNT(?report) AS ?occurrenceCount) ?sideEffectLabel
WHERE {
  ?drug rdfs:label "Ibuprofen"@en .
  ?report wu:reportConcernsDrug ?drug .
  ?report wu:reportInvolvesPatient ?patient .
  ?patient wu:patientExperiencedSideEffect ?sideEffectNode .
  ?sideEffectNode rdfs:label ?sideEffectLabel .
}
GROUP BY ?sideEffectLabel
HAVING (COUNT(?report) > 1)
ORDER BY DESC(?occurrenceCount)