PREFIX wu: <http://www.semanticweb.org/zerda/ontologies/2025/6/ontology_painkiller/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?painkillerLabel (COUNT(?report) AS ?occurrenceCount) ?sideEffectLabel
WHERE {
  ?drug a wu:Drug;
        rdfs:label ?painkillerLabel .
  ?report wu:reportConcernsDrug ?drug .
  ?report wu:reportInvolvesPatient ?patient .
  ?patient wu:patientExperiencedSideEffect ?sideEffectNode .
  ?sideEffectNode rdfs:label ?sideEffectLabel .
}
GROUP BY ?painkillerLabel ?sideEffectLabel
HAVING (COUNT(?report) > 1)
ORDER BY ?painkillerLabel DESC(?occurrenceCount)