PREFIX wu: <http://www.semanticweb.org/zerda/ontologies/2025/6/ontology_painkiller/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?painkillerLabel ?fatalPercentage
WHERE {
  ?painkiller a wu:Drug ;
              rdfs:label ?painkillerLabel ;
              wu:fatalReportPercentage ?fatalPercentage .
}
ORDER BY DESC(?fatalPercentage)